FROM python:3.7

# Install pip libraries
ADD requirements-SOTA.txt requirements.txt
RUN pip install -r requirements.txt

# Load objects library.
ADD source/objects /aiq-sail-on/objects/

# Load SOTA.py
ADD source/sota_util /aiq-sail-on/sota_util/
ADD source/SOTA-cartpole.py /aiq-sail-on/SOTA-cartpole.py
ADD source/SOTA-vizdoom.py /aiq-sail-on/SOTA-vizdoom.py

# Change local dir
WORKDIR /aiq-sail-on/
