FROM python:3.7

# Install pip libraries
ADD requirements-SOTA.txt requirements.txt
RUN pip install -r requirements.txt

# Load objects library.
ADD source/objects /aiq-sail-on/objects/

# Load SOTA.py
ADD source/random_action.py /aiq-sail-on
ADD source/sample-cartpole.py /aiq-sail-on
ADD source/sample-vizdoom.py /aiq-sail-on

# Change local dir
WORKDIR /aiq-sail-on/
